/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Order Flow API
 * API for managing order flow
 * OpenAPI spec version: 1.0
 */

export interface FullStoreDto {
  address: string;
  city: string;
  createdAt: string;
  email: string;
  id: string;
  name: string;
  phone: string;
  state: string;
  updatedAt: string;
  website: string;
  zip: string;
}
