/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Order Flow API
 * API for managing order flow
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import {
  computed,
  unref
} from 'vue'
import type {
  MaybeRef
} from 'vue'
import type {
  FullStoreDto
} from '../../model'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



export const storeControllerGetStore = (
    uuid: MaybeRef<string>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FullStoreDto>> => {
    uuid = unref(uuid);
    return axios.get(
      `/store/${uuid}`,options
    );
  }


export const getStoreControllerGetStoreQueryKey = (uuid: MaybeRef<string>,) => {
    return ['store',uuid] as const;
    }

    
export const getStoreControllerGetStoreQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStore>>, TError = AxiosError<FullStoreDto>>(uuid: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getStoreControllerGetStoreQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStore>>> = ({ signal }) => storeControllerGetStore(uuid, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uuid))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData> 
}

export type StoreControllerGetStoreQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStore>>>
export type StoreControllerGetStoreQueryError = AxiosError<FullStoreDto>



export function useStoreControllerGetStore<TData = Awaited<ReturnType<typeof storeControllerGetStore>>, TError = AxiosError<FullStoreDto>>(
 uuid: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStore>>, TError, TData>>, axios?: AxiosRequestConfig}

  ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStoreControllerGetStoreQueryOptions(uuid,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}



export const storeControllerCreateStore = (
    fullStoreDto: MaybeRef<FullStoreDto>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FullStoreDto>> => {
    fullStoreDto = unref(fullStoreDto);
    return axios.post(
      `/store`,
      fullStoreDto,options
    );
  }



export const getStoreControllerCreateStoreMutationOptions = <TError = AxiosError<FullStoreDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeControllerCreateStore>>, TError,{data: FullStoreDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof storeControllerCreateStore>>, TError,{data: FullStoreDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeControllerCreateStore>>, {data: FullStoreDto}> = (props) => {
          const {data} = props ?? {};

          return  storeControllerCreateStore(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StoreControllerCreateStoreMutationResult = NonNullable<Awaited<ReturnType<typeof storeControllerCreateStore>>>
    export type StoreControllerCreateStoreMutationBody = FullStoreDto
    export type StoreControllerCreateStoreMutationError = AxiosError<FullStoreDto>

    export const useStoreControllerCreateStore = <TError = AxiosError<FullStoreDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeControllerCreateStore>>, TError,{data: FullStoreDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationReturnType<
        Awaited<ReturnType<typeof storeControllerCreateStore>>,
        TError,
        {data: FullStoreDto},
        TContext
      > => {

      const mutationOptions = getStoreControllerCreateStoreMutationOptions(options);

      return useMutation(mutationOptions);
    }
    